execute pathogen#infect()
syntax on
filetype plugin indent on

" Reform search.
set ignorecase
set smartcase

" Avoid the leader pinky-stretch.
let mapleader = ","
let maplocalleader = ","

" Visually indicate when we're in insert mode.
autocmd InsertEnter * set cursorline
autocmd InsertLeave * set nocursorline

" No tabs!
set tabstop=2
set shiftwidth=2
set expandtab

" Backups
set nobackup
set noswapfile

" Nerd tree
nmap <LocalLeader>nt :NERDTreeToggle<CR>
nmap <LocalLeader>f :NERDTreeFind<CR>

" Nerd tree tabs - open only if directory was given as a startup argument
let g:nerdtree_tabs_open_on_console_startup=2

" Colours
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

" Keep status line visible, as we're using Airline.
set laststatus=2

" vim-better-whitespace
" strip all trailing whitespace everytime you save the file for all file types
autocmd BufEnter * EnableStripWhitespaceOnSave

" Paredit
let g:paredit_mode = 1

" Rainbow parens
autocmd VimEnter * RainbowParenthesesToggle
autocmd Syntax * RainbowParenthesesLoadRound
autocmd Syntax * RainbowParenthesesLoadSquare
autocmd Syntax * RainbowParenthesesLoadBraces

" Surround
nmap <LocalLeader>w" ysiw"
nmap <LocalLeader>w' ysiw'
nmap <LocalLeader>w( ysiw)
nmap <LocalLeader>w[ ysiw]
